parameters: 
  - name: personaId
  - name: podId
  - name: podResourceGroup


jobs: 

  - job: Read_HostPool_for_${{ parameters.podId }}
    displayName: Get information for HostPool of ${{ parameters.podId }}
    steps: 
      - task: AzurePowerShell@4
        name: Get_Information_for_HostPool_in_${{ parameters.podId }}
        displayName: Get info for HostPool in ${{ parameters.podId }}
        inputs: 
          pwsh: true
          azureSubscription: $(serviceConnection)
          scriptType: filePath
          azurePowerShellVersion: "LatestVersion"
          scriptPath: $(Build.Repository.LocalPath)\scripts\Read-HostPool.ps1
          scriptArguments: -ResourceGroupName ${{ parameters.podResourceGroup }}  -HostPoolName ${{ parameters.personaId }}-${{ parameters.podId }}-Pool