# Pipleine for user group management for multiple PODs in Persona

trigger:
  - none

pr:
  - none

pool:
  vmImage: $[ variables.vmWinImage ]

parameters:
  - name: persona
    displayName: Persona
    type: string
    values:
      - PR01
      - PR02

  - name: action
    displayName: Action
    type: string
    values: 
      - Add
      - Remove

extends:
  template: ../config/Persona/${{ parameters.persona }}.yml
  parameters: 
    userManagement: true
    action: ${{ parameters.action }} 


